"""add_auth_columns_to_doctors

Revision ID: 580f750e3f43
Revises: 
Create Date: 2026-04-12 19:55:56.562139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '580f750e3f43'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.drop_constraint(op.f('doctors_username_key'), 'doctors', type_='unique')
    op.create_index(op.f('ix_doctors_username'), 'doctors', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctors_username'), table_name='doctors')
    op.create_unique_constraint(op.f('doctors_username_key'), 'doctors', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_column('doctors', 'created_at')
    # ### end Alembic commands ###
